issuer: https://token.actions.githubusercontent.com
subject: repo:jakebailey/every-ts:ref:refs/heads/main
claim_pattern:
  workflow_ref: jakebailey/every-ts/\.github/workflows/release\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
