name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          filter: blob:none

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '*'
          package-manager-cache: false

      - run: npm install -g npm@latest

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: pnpm install
        run: pnpm install

      - name: Capture new release version
        id: version
        run: |
          pnpm changeset version
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
          git restore .

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: jakebailey/every-ts
          identity: release

      - uses: changesets/action@v1
        with:
          title: 'Release v${{ steps.version.outputs.version }}'
          commit: 'Release v${{ steps.version.outputs.version }}'
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
